//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diet.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new food...
        /// </summary>
        public static string AddNewFood {
            get {
                return ResourceManager.GetString("AddNewFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new food from website...
        /// </summary>
        public static string AddNewFoodFromSite {
            get {
                return ResourceManager.GetString("AddNewFoodFromSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string AnotherLanguage {
            get {
                return ResourceManager.GetString("AnotherLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1.
        /// </summary>
        public static string B1 {
            get {
                return ResourceManager.GetString("B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B12.
        /// </summary>
        public static string B12 {
            get {
                return ResourceManager.GetString("B12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2.
        /// </summary>
        public static string B2 {
            get {
                return ResourceManager.GetString("B2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B3.
        /// </summary>
        public static string B3 {
            get {
                return ResourceManager.GetString("B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B5.
        /// </summary>
        public static string B5 {
            get {
                return ResourceManager.GetString("B5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B6.
        /// </summary>
        public static string B6 {
            get {
                return ResourceManager.GetString("B6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B7.
        /// </summary>
        public static string B7 {
            get {
                return ResourceManager.GetString("B7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B9.
        /// </summary>
        public static string B9 {
            get {
                return ResourceManager.GetString("B9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcium.
        /// </summary>
        public static string Calcium {
            get {
                return ResourceManager.GetString("Calcium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        public static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbohydrats.
        /// </summary>
        public static string Carbohydrats {
            get {
                return ResourceManager.GetString("Carbohydrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chlorine.
        /// </summary>
        public static string Chlorine {
            get {
                return ResourceManager.GetString("Chlorine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium.
        /// </summary>
        public static string Chromium {
            get {
                return ResourceManager.GetString("Chromium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper.
        /// </summary>
        public static string Copper {
            get {
                return ResourceManager.GetString("Copper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DieteryFiber.
        /// </summary>
        public static string DieteryFiber {
            get {
                return ResourceManager.GetString("DieteryFiber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fats.
        /// </summary>
        public static string Fats {
            get {
                return ResourceManager.GetString("Fats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluorine.
        /// </summary>
        public static string Fluorine {
            get {
                return ResourceManager.GetString("Fluorine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macronutrients.
        /// </summary>
        public static string FoodBZHU {
            get {
                return ResourceManager.GetString("FoodBZHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string FoodGeneral {
            get {
                return ResourceManager.GetString("FoodGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string FoodMax {
            get {
                return ResourceManager.GetString("FoodMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FoodName {
            get {
                return ResourceManager.GetString("FoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        public static string Gramm {
            get {
                return ResourceManager.GetString("Gramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iodine.
        /// </summary>
        public static string Iodine {
            get {
                return ResourceManager.GetString("Iodine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron.
        /// </summary>
        public static string Iron {
            get {
                return ResourceManager.GetString("Iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        public static string K {
            get {
                return ResourceManager.GetString("K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link:.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i.e. https://health-diet.ru/table_calorie_users/515620/.
        /// </summary>
        public static string LinkExample {
            get {
                return ResourceManager.GetString("LinkExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnesium.
        /// </summary>
        public static string Magnesium {
            get {
                return ResourceManager.GetString("Magnesium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manganese.
        /// </summary>
        public static string Manganese {
            get {
                return ResourceManager.GetString("Manganese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mcg.
        /// </summary>
        public static string Microgramm {
            get {
                return ResourceManager.GetString("Microgramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micronutrients.
        /// </summary>
        public static string Micronutrients {
            get {
                return ResourceManager.GetString("Micronutrients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg.
        /// </summary>
        public static string Milligramm {
            get {
                return ResourceManager.GetString("Milligramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molybdenum.
        /// </summary>
        public static string Molybdenum {
            get {
                return ResourceManager.GetString("Molybdenum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumbersAndWords.
        /// </summary>
        public static string NumbersAndWords {
            get {
                return ResourceManager.GetString("NumbersAndWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega 3.
        /// </summary>
        public static string Omega3 {
            get {
                return ResourceManager.GetString("Omega3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega 6.
        /// </summary>
        public static string Omega6 {
            get {
                return ResourceManager.GetString("Omega6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosphorus.
        /// </summary>
        public static string Phosphorus {
            get {
                return ResourceManager.GetString("Phosphorus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potassium.
        /// </summary>
        public static string Potassium {
            get {
                return ResourceManager.GetString("Potassium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proteins.
        /// </summary>
        public static string Proteins {
            get {
                return ResourceManager.GetString("Proteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selenium.
        /// </summary>
        public static string Selenium {
            get {
                return ResourceManager.GetString("Selenium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodium.
        /// </summary>
        public static string Sodium {
            get {
                return ResourceManager.GetString("Sodium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulfur.
        /// </summary>
        public static string Sulfur {
            get {
                return ResourceManager.GetString("Sulfur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamins.
        /// </summary>
        public static string Vitamins {
            get {
                return ResourceManager.GetString("Vitamins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website is not available.
        /// </summary>
        public static string WebsiteNotAvailable {
            get {
                return ResourceManager.GetString("WebsiteNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your weight:.
        /// </summary>
        public static string YourWeight {
            get {
                return ResourceManager.GetString("YourWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zink.
        /// </summary>
        public static string Zink {
            get {
                return ResourceManager.GetString("Zink", resourceCulture);
            }
        }
    }
}
